export type WorkflowStage =
    | "Planning"
    | "KnowledgeRetrieval"
    | "InteractiveQuestions"
    | "VariableCapture"
    | "BusinessRetry"
    | "ValidationPlanning"
    | "PromptBuild"
    | "LLM"
    | "Review"
    | "AutoFix"
    | "Approval"
    | "ArtifactGeneration"
    | "WriteFiles"
    | "History"
    | "Done";
